services:
  app:
    image: registry-harbor.ubos.vn/github-demo/vione:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vione-app
    restart: always
    ports:
      - "5000:4000"
    env_file:
      - .env
