services:
  app:
    image: registry-harbor.ubos.vn/github-demo/qlhh:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-demo-qlhh
    restart: always
    ports:
      - "5000:4000"
    env_file:
      - .env
