const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const COMPANY_ENRICHMENTS = {
  'M1983-001': {
    name: 'Tập đoàn Công nghệ ViOne Cloud',
    contact: 'Nguyễn Thanh Tuấn',
    tax_code: '0101983001',
    website: 'https://vione.vn',
    employees: 450,
    industry: 'ind.it',
    region: 'region.north',
    address: 'Tòa nhà ViOne Tower, Cầu Giấy, Hà Nội',
    about: 'Nền tảng hợp nhất quản trị và kết nối hệ sinh thái doanh nghiệp B2B thế hệ mới tại Việt Nam.',
  },
  'M1983-002': {
    name: 'Tập đoàn Uranus Tech Global',
    contact: 'James Nguyễn',
    tax_code: '0101983002',
    website: 'https://uranustech.vn',
    employees: 320,
    industry: 'ind.it',
    region: 'region.north',
    address: 'Tầng 18 Keangnam Landmark 72, Nam Từ Liêm, Hà Nội',
    about: 'Tập đoàn công nghệ chuyên cung cấp giải pháp AI, Big Data và chuyển đổi số cho doanh nghiệp đa quốc gia.',
  },
  'M1983-003': {
    name: 'Công ty CP Đầu tư & Công nghệ Uranus',
    contact: 'James Nguyễn',
    tax_code: '0101983003',
    website: 'https://uranus.group',
    employees: 180,
    industry: 'ind.finance',
    region: 'region.north',
    address: 'Tháp Lotte Center, Ba Đình, Hà Nội',
    about: 'Quỹ đầu tư công nghệ và tài chính hỗ trợ các doanh nghiệp khởi nghiệp đổi mới sáng tạo.',
  },
  'M1983-004': {
    name: 'Công ty CP Giải pháp Phần mềm ViOne Software',
    contact: 'Lê Minh Quân',
    tax_code: '0101983004',
    website: 'https://software.vione.vn',
    employees: 210,
    industry: 'ind.it',
    region: 'region.north',
    address: 'Duy Tân, Cầu Giấy, Hà Nội',
    about: 'Cung cấp hệ thống CRM & ERP tinh gọn cho các hiệp hội và tổ chức doanh nghiệp.',
  },
  'M1983-005': {
    name: 'Công ty TNHH Thương mại Quốc tế Hoàng Nam',
    contact: 'Nguyễn Hoàng Nam',
    tax_code: '0101983005',
    website: 'https://hoangnamtrade.vn',
    employees: 160,
    industry: 'ind.trade',
    region: 'region.north',
    address: 'Phố Huế, Hai Bà Trưng, Hà Nội',
    about: 'Xuất nhập khẩu và phân phối hàng tiêu dùng cao cấp, xúc tiến thương mại song phương.',
  },
  'M1983-006': {
    name: 'Công ty CP Chuỗi Cung ứng Toàn Cầu Thu Thảo',
    contact: 'Trần Thu Thảo',
    tax_code: '0101983006',
    website: 'https://thuthaologistics.vn',
    employees: 280,
    industry: 'ind.trade',
    region: 'region.north',
    address: 'Nguyễn Trãi, Thanh Xuân, Hà Nội',
    about: 'Dịch vụ kho bãi, logistics thông minh và chuỗi cung ứng lạnh tiêu chuẩn quốc tế.',
  },
  'M1983-007': {
    name: 'Công ty CP Công nghệ & Giải pháp Long Tech',
    contact: 'Lê Hoàng Long',
    tax_code: '0101983007',
    website: 'https://longtech.vn',
    employees: 350,
    industry: 'ind.it',
    region: 'region.north',
    address: 'Tòa nhà Viwaseen, Nam Từ Liêm, Hà Nội',
    about: 'Tư vấn kiến trúc hệ thống dữ liệu đám mây và an ninh thông tin doanh nghiệp.',
  },
  'M1983-008': {
    name: 'Công ty TNHH Sản xuất & Thương mại Cường Thịnh',
    contact: 'Nguyễn Văn Cường',
    tax_code: '0101983008',
    website: 'https://cuongthinhcorp.com',
    employees: 420,
    industry: 'ind.manufacturing',
    region: 'region.north',
    address: 'KCN Bắc Thăng Long, Đông Anh, Hà Nội',
    about: 'Sản xuất linh kiện phụ trợ chính xác và cung cấp dây chuyền gia công tự động hóa.',
  },
  'M1983-009': {
    name: 'Công ty CP Tài chính & Đầu tư An Bình Wealth',
    contact: 'Vũ Thu Trang',
    tax_code: '0101983009',
    website: 'https://anbinhwealth.vn',
    employees: 120,
    industry: 'ind.finance',
    region: 'region.north',
    address: 'Lý Thường Kiệt, Hoàn Kiếm, Hà Nội',
    about: 'Tư vấn tái cấu trúc tài chính doanh nghiệp, M&A và quản lý tài sản tư nhân.',
  },
  'M1983-010': {
    name: 'Tập đoàn Truyền thông & Sự kiện CEO1983',
    contact: 'Phạm Quang Huy',
    tax_code: '0101983010',
    website: 'https://ceo1983.com',
    employees: 190,
    industry: 'ind.trade',
    region: 'region.north',
    address: 'Võ Chí Công, Tây Hồ, Hà Nội',
    about: 'Tổ chức sự kiện kinh doanh cấp cao, hội nghị kết nối giao thương B2B toàn quốc.',
  },
  'M1983-011': {
    name: 'Công ty CP Bất Động Sản & Xây Dựng Tuấn Hưng',
    contact: 'Hoàng Minh Tuấn',
    tax_code: '0101983011',
    website: 'https://tuanhungland.vn',
    employees: 230,
    industry: 'ind.realestate',
    region: 'region.north',
    address: 'Lê Văn Lương, Cầu Giấy, Hà Nội',
    about: 'Phát triển bất động sản khu công nghiệp và hạ tầng phụ trợ logistic hiện đại.',
  },
  'M1983-012': {
    name: 'Công ty TNHH Dịch vụ & Du lịch Quốc tế Mai Travel',
    contact: 'Đỗ Thị Mai',
    tax_code: '0101983012',
    website: 'https://maitravel.vn',
    employees: 140,
    industry: 'ind.trade',
    region: 'region.north',
    address: 'Trần Hưng Đạo, Hoàn Kiếm, Hà Nội',
    about: 'Dịch vụ lữ hành MICE cao cấp và các đoàn xúc tiến thương mại quốc tế.',
  },
  'M1983-013': {
    name: 'Công ty CP Kỹ thuật & Tự động hóa Đức Thắng',
    contact: 'Bùi Đức Thắng',
    tax_code: '0101983013',
    website: 'https://ducthangauto.vn',
    employees: 310,
    industry: 'ind.manufacturing',
    region: 'region.north',
    address: 'KCN Quang Minh, Mê Linh, Hà Nội',
    about: 'Giải pháp robot công nghiệp và điều khiển tự động trong sản xuất.',
  },
  'M1983-014': {
    name: 'Công ty CP Dược phẩm & Thiết bị Y tế Bảo Anh',
    contact: 'Ngô Bảo Anh',
    tax_code: '0101983014',
    website: 'https://baoanhpharma.com',
    employees: 260,
    industry: 'ind.trade',
    region: 'region.north',
    address: 'Giải Phóng, Hoàng Mai, Hà Nội',
    about: 'Nhập khẩu và phân phối thiết bị y tế tiêu chuẩn châu Âu cho các bệnh viện lớn.',
  },
  'M1983-015': {
    name: 'Công ty TNHH Tư vấn Quản lý Trọng Hiếu',
    contact: 'Đinh Trọng Hiếu',
    tax_code: '0101983015',
    website: 'https://tronghieuconsulting.vn',
    employees: 85,
    industry: 'ind.trade',
    region: 'region.north',
    address: 'Kim Mã, Ba Đình, Hà Nội',
    about: 'Đào tạo lãnh đạo cấp cao, tối ưu hóa quy trình vận hành và văn hóa doanh nghiệp.',
  },
  'M1983-016': {
    name: 'Công ty CP Nông sản Sạch & Xuất Khẩu Kim Oanh',
    contact: 'Trịnh Kim Oanh',
    tax_code: '0101983016',
    website: 'https://kimoanhfoods.vn',
    employees: 390,
    industry: 'ind.manufacturing',
    region: 'region.north',
    address: 'Hoàng Quốc Việt, Cầu Giấy, Hà Nội',
    about: 'Chế biến và xuất khẩu nông sản sạch đạt tiêu chuẩn GlobalGAP sang thị trường EU và Mỹ.',
  },
  'M1983-100': {
    name: 'Tập đoàn Công nghệ Kho Group',
    contact: 'Đặng Minh Khôi',
    tax_code: '0109988776',
    website: 'https://khoiminh.tech',
    employees: 250,
    industry: 'ind.it',
    region: 'region.north',
    address: 'Tầng 12 ViOne Tech Hub, Cầu Giấy, Hà Nội',
    about: 'Hệ sinh thái phần mềm quản trị toàn diện và chuyển đổi số cho doanh nghiệp SME.',
  },
};

async function main() {
  console.log('Enriching company data for members...');
  for (const [code, info] of Object.entries(COMPANY_ENRICHMENTS)) {
    const res = await p.members.updateMany({
      where: { code },
      data: {
        name: info.name,
        contact: info.contact,
        tax_code: info.tax_code,
        website: info.website,
        employees: info.employees,
        industry: info.industry,
        region: info.region,
        address: info.address,
        about: info.about,
        type: 'company',
      },
    });
    console.log(`Updated ${code} -> ${info.name} (${res.count} rows)`);
  }
  console.log('Enrichment completed successfully!');
}

main().catch(console.error).finally(() => p.$disconnect());
