import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import type { Member } from "./members-data";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

type Row = Record<string, unknown>;

function mapRow(r: Row): Member {
  return {
    id: r.id as string,
    code: r.code as string,
    name: r.name as string,
    contact: (r.contact as string) ?? "",
    email: (r.email as string) ?? "",
    phone: (r.phone as string) ?? "",
    type: r.type as Member["type"],
    level: r.level as Member["level"],
    industry: r.industry as Member["industry"],
    region: r.region as Member["region"],
    status: r.status as Member["status"],
    joinedAt: r.joined_at as string,
    feeYear: r.fee_year as number,
    feePaid: r.fee_paid as boolean,
    address: (r.address as string) ?? "",
    website: (r.website as string) ?? undefined,
    taxCode: (r.tax_code as string) ?? undefined,
    employees: (r.employees as number) ?? undefined,
    about: (r.about as string) ?? "",
    termEnd: (r.term_end as string) ?? undefined,
    reminderCount: (r.reminder_count as number) ?? 0,
    lastReminder: (r.last_reminder as string) ?? undefined,
    renewedAt: (r.renewed_at as string) ?? undefined,
    newTermEnd: (r.new_term_end as string) ?? undefined,
  };
}

export const listMembersFn = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { getActiveAssociationId } = await import("./assoc-scope.server");
    const activeId = await getActiveAssociationId(context.supabase);
    let query = context.supabase.from("members").select("*").order("code", { ascending: true });
    if (activeId) query = query.eq("association_id", activeId);
    const { data, error } = await query;
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapRow);
  });

// Role-aware peer list for Networking. Returns only non-sensitive fields,
// scoped to the caller's active association. Works for regular members too
// (the base members table stays admin-only / self-only via RLS).
function mapPeerRow(r: Row): Member {
  return {
    id: r.id as string,
    code: (r.code as string) ?? "",
    name: r.name as string,
    contact: "",
    email: "",
    phone: "",
    type: (r.type as Member["type"]) ?? "company",
    level: (r.level as Member["level"]) ?? "memberLevel.medium",
    industry: (r.industry as Member["industry"]) ?? "ind.trade",
    region: (r.region as Member["region"]) ?? "region.north",
    status: (r.status as Member["status"]) ?? "active",
    joinedAt: "",
    feeYear: new Date().getFullYear(),
    feePaid: false,
    address: "",
    about: "",
  };
}

export const listPeersFn = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }): Promise<Member[]> => {
    const { data, error } = await context.supabase.rpc("list_peers");
    if (error) throw new Error(error.message);
    return ((data ?? []) as Row[]).map(mapPeerRow);
  });

export const createMemberFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) =>
    z
      .object({
        name: z.string().min(1).max(255),
        contact: z.string().max(255).optional(),
        email: z.string().max(255).optional(),
        phone: z.string().max(64).optional(),
        type: z.enum(["company", "individual"]).default("company"),
        level: z
          .enum([
            "memberLevel.large",
            "memberLevel.medium",
            "memberLevel.small",
            "memberLevel.individual",
          ])
          .default("memberLevel.medium"),
        industry: z
          .enum(["ind.trade", "ind.it", "ind.manufacturing", "ind.realestate", "ind.finance"])
          .default("ind.trade"),
        region: z.enum(["region.north", "region.central", "region.south"]).default("region.north"),
        status: z.enum(["active", "pending", "expired"]).default("pending"),
        address: z.string().max(500).optional(),
        website: z.string().max(255).optional(),
        taxCode: z.string().max(64).optional(),
        employees: z.coerce.number().int().nonnegative().optional(),
        about: z.string().max(2000).optional(),
      })
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const now = new Date();
    const id = `MB${now.getTime().toString(36).toUpperCase()}`;
    // code is generated by the DB trigger (PREFIX-00000x per association)
    const { data: row, error } = await context.supabase
      .from("members")
      .insert({
        id,
        code: "",
        name: data.name,
        contact: data.contact ?? "",
        email: data.email ?? "",
        phone: data.phone ?? "",
        type: data.type,
        level: data.level,
        industry: data.industry,
        region: data.region,
        status: data.status,
        joined_at: now.toISOString().slice(0, 10),
        fee_year: now.getFullYear(),
        fee_paid: false,
        address: data.address ?? "",
        website: data.website,
        tax_code: data.taxCode,
        employees: data.employees,
        about: data.about ?? "",
      })
      .select("*")
      .maybeSingle();
    if (error) throw new Error(error.message);
    return row ? mapRow(row) : null;
  });

export const getMemberFn = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => z.object({ id: z.string().min(1).max(64) }).parse(d))
  .handler(async ({ data, context }) => {
    const { data: row, error } = await context.supabase
      .from("members")
      .select("*")
      .eq("id", data.id)
      .maybeSingle();
    if (error) throw new Error(error.message);
    return row ? mapRow(row) : null;
  });

export const updateMemberFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) =>
    z
      .object({
        id: z.string().min(1).max(64),
        name: z.string().min(1).max(255),
        contact: z.string().max(255).optional(),
        email: z.string().max(255).optional(),
        phone: z.string().max(64).optional(),
        type: z.enum(["company", "individual"]).default("company"),
        level: z
          .enum([
            "memberLevel.large",
            "memberLevel.medium",
            "memberLevel.small",
            "memberLevel.individual",
          ])
          .default("memberLevel.medium"),
        industry: z
          .enum(["ind.trade", "ind.it", "ind.manufacturing", "ind.realestate", "ind.finance"])
          .default("ind.trade"),
        region: z.enum(["region.north", "region.central", "region.south"]).default("region.north"),
        status: z.enum(["active", "pending", "expired"]).default("pending"),
        address: z.string().max(500).optional(),
        website: z.string().max(255).optional(),
        taxCode: z.string().max(64).optional(),
        employees: z.coerce.number().int().nonnegative().optional(),
        about: z.string().max(2000).optional(),
      })
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const { data: row, error } = await context.supabase
      .from("members")
      .update({
        name: data.name,
        contact: data.contact ?? "",
        email: data.email ?? "",
        phone: data.phone ?? "",
        type: data.type,
        level: data.level,
        industry: data.industry,
        region: data.region,
        status: data.status,
        address: data.address ?? "",
        website: data.website,
        tax_code: data.taxCode,
        employees: data.employees,
        about: data.about ?? "",
      })
      .eq("id", data.id)
      .select("*")
      .maybeSingle();
    if (error) throw new Error(error.message);
    return row ? mapRow(row) : null;
  });

export const deleteMemberFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => z.object({ id: z.string().min(1).max(64) }).parse(d))
  .handler(async ({ data, context }) => {
    const { error } = await context.supabase.from("members").delete().eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

export const updateMemberContactFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) =>
    z
      .object({
        id: z.string().min(1).max(64),
        email: z.string().email().max(255).optional(),
        phone: z.string().max(64).optional(),
        address: z.string().max(500).optional(),
      })
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const patch: { email?: string; phone?: string; address?: string } = {};
    if (data.email !== undefined) patch.email = data.email;
    if (data.phone !== undefined) patch.phone = data.phone;
    if (data.address !== undefined) patch.address = data.address;
    const { data: row, error } = await context.supabase
      .from("members")
      .update(patch)
      .eq("id", data.id)
      .select("*")
      .maybeSingle();
    if (error) throw new Error(error.message);
    return row ? mapRow(row) : null;
  });

export const renewMembershipFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => z.object({ id: z.string().min(1).max(64) }).parse(d))
  .handler(async ({ data, context }) => {
    const { data: cur, error: e1 } = await context.supabase
      .from("members")
      .select("term_end")
      .eq("id", data.id)
      .maybeSingle();
    if (e1) throw new Error(e1.message);
    if (!cur) return null;
    const base = cur.term_end ? new Date(cur.term_end as string) : new Date();
    const newEnd = new Date(base);
    newEnd.setFullYear(newEnd.getFullYear() + 1);
    const today = new Date().toISOString().slice(0, 10);
    const { data: row, error } = await context.supabase
      .from("members")
      .update({
        fee_paid: true,
        renewed_at: today,
        new_term_end: newEnd.toISOString().slice(0, 10),
      })
      .eq("id", data.id)
      .select("*")
      .maybeSingle();
    if (error) throw new Error(error.message);
    return row ? mapRow(row) : null;
  });

export const sendRenewalReminderFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => z.object({ id: z.string().min(1).max(64) }).parse(d))
  .handler(async ({ data, context }) => {
    const { data: cur, error: e1 } = await context.supabase
      .from("members")
      .select("reminder_count")
      .eq("id", data.id)
      .maybeSingle();
    if (e1) throw new Error(e1.message);
    if (!cur) return null;
    const today = new Date().toISOString().slice(0, 10);
    const { data: row, error } = await context.supabase
      .from("members")
      .update({
        reminder_count: ((cur.reminder_count as number) ?? 0) + 1,
        last_reminder: today,
      })
      .eq("id", data.id)
      .select("*")
      .maybeSingle();
    if (error) throw new Error(error.message);
    return row ? mapRow(row) : null;
  });
