// Guarded service-worker registration for offline support.
// The worker (/sw.js) is generated by vite-plugin-pwa (generateSW).
// It is ONLY registered in the real published app — never in dev, iframes,
// or Lovable preview hosts, where it could serve stale HTML/chunks.

const SW_URL = "/sw.js";

function isRefusedContext(): boolean {
  if (!import.meta.env.PROD) return true;
  if (typeof window === "undefined") return true;

  // Inside an iframe (Lovable editor preview).
  try {
    if (window.self !== window.top) return true;
  } catch {
    return true;
  }

  const url = new URL(window.location.href);
  if (url.searchParams.get("sw") === "off") return true;

  const host = window.location.hostname;
  if (host.startsWith("id-preview--") || host.startsWith("preview--")) return true;
  if (host === "lovableproject.com" || host.endsWith(".lovableproject.com")) return true;
  if (host === "lovableproject-dev.com" || host.endsWith(".lovableproject-dev.com")) return true;
  if (host === "beta.lovable.dev" || host.endsWith(".beta.lovable.dev")) return true;

  return false;
}

const EXPECTED_SCOPE = "/";

function isOurWorker(r: ServiceWorkerRegistration) {
  const script = r.active?.scriptURL ?? r.waiting?.scriptURL ?? r.installing?.scriptURL ?? "";
  return script.endsWith(SW_URL);
}

async function unregisterMatching() {
  if (!("serviceWorker" in navigator)) return;
  const regs = await navigator.serviceWorker.getRegistrations();
  await Promise.allSettled(regs.filter(isOurWorker).map((r) => r.unregister()));
}

/**
 * The app ships a single root-scoped worker. A narrower registration (e.g.
 * scope `/connect-app/` or `/vione-app/`) left over from an older install
 * would take precedence for those paths and could serve the wrong app shell
 * when ViOne App is launched from a home-screen shortcut. Drop any such
 * stray registration so only the root-scoped worker controls navigation.
 */
async function pruneStrayScopes() {
  if (!("serviceWorker" in navigator)) return;
  const regs = await navigator.serviceWorker.getRegistrations();
  const strays = regs.filter((r) => {
    if (!isOurWorker(r)) return false;
    try {
      return new URL(r.scope).pathname !== EXPECTED_SCOPE;
    } catch {
      return false;
    }
  });
  await Promise.allSettled(strays.map((r) => r.unregister()));
}

export function registerServiceWorker() {
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;

  if (isRefusedContext()) {
    void unregisterMatching();
    return;
  }

  void pruneStrayScopes().then(() =>
    import("virtual:pwa-register").then(({ registerSW }) => {
      registerSW({ immediate: true });
    }),
  );
}

